version: '3.8'

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./blocked_urls.conf:/etc/nginx/blocked_urls.conf # Список запрещённых URL
      - ./forbidden_requests.log:/var/log/nginx/forbidden_requests.log # Логи обращений к запрещенным URL
      - ./fail2ban_redirect.conf:/etc/nginx/fail2ban_redirect.conf
    networks:
      - test_network

  fail2ban:
    build:
      context: .
      dockerfile: Dockerfile.fail2ban
    volumes:
      - ./forbidden_requests.log:/var/log/nginx/forbidden_requests.log # Логи обращений к запрещенным URL
      - ./fail2ban_redirect.conf:/etc/nginx/fail2ban_redirect.conf
    networks:
      - test_network
    privileged: true
    user: root
    restart: unless-stopped

networks:
  test_network:
    driver: bridge